version: "3.9"

services:
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      # Kalau node_modules sering bikin conflict di host ↔ container,
      # bisa pakai anonymous volume biar bersih
      - /app/node_modules
    command: sh -lc "npm ci && npm test"
    tty: true
    stdin_open: true
    env_file:
      - .env
    environment:
    - BROWSER=${BROWSER:-chrome}
    - BASE_URL=${BASE_URL:-http://localhost:3000}
    - USER_NAME=${USER_NAME:-standard_user}
    - PASSWORD=${PASSWORD:-secret_sauce}
